# Generated by Django 5.1.6 on 2025-02-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_delete_article_alter_news_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
    ]
