# Generated by Django 5.1.6 on 2025-03-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_comment_content_alter_comment_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='cool', max_length=200),
        ),
    ]
